Add AI/LLM generated tests
homieiot/homie-testsuite pull request #4
Opened 2024-11-19 13:41 UTC by nstadigs

I gave convention.md together with the already created tests GPT-4o.

Didn't get to datetime, duration and JSON because my free tier ran out for the day.

These needs to be validated!

2024-11-19 13:43 UTC, nstadigs commented on homie5/values/string.yml
> +  #   valid: false
Can these tests be represented in yaml somehow?

2024-11-19 13:45 UTC, nstadigs commented
rofl @Tieske already did this https://github.com/homieiot/homie-testsuite/pull/3 :laughing: 

Closing

2024-11-19 18:53 UTC, Tieske commented
some of mine were placeholder files, so maybe we can still use some of this as well

2024-11-20 18:04 UTC, nstadigs commented
Alright. When yours are merged I can rebase these on top

2024-11-20 18:09 UTC, Tieske commented
Can you review the other PR? if ok, I'll merge it

2024-11-22 14:21 UTC, Tieske commented
can you rebase this? the formats are duplicates by now, but the values are probably filling in the placeholders I put in there

2024-11-22 14:23 UTC, nstadigs commented
> can you rebase this? the formats are duplicates by now, but the values are probably filling in the placeholders I put in there

Yeah, I plan to continue on this when I get some spare time. It's in draft mode for now

2024-12-02 11:26 UTC, Tieske requested changes
Here's a start for a review. Though incomplete.

floats need tests on exponential notation and missing lead-zero's, eg ".001" and "-.1" are valid (imho)

also need to verify the range tests still.

2024-12-02 11:26 UTC, Tieske commented on homie5/formats/float.yml
> +    valid: false
```suggestion
  - description: missing range boundaries are accepted
    testtype: propertydescription
    definition:
      datatype: float
      format: ":"
    valid: true
```

This one should be accepted, since it is the default format.

2024-12-02 11:26 UTC, Tieske commented on homie5/formats/float.yml
> +
```suggestion

  - description: proper format with only step value is accepted
    testtype: propertydescription
    definition:
      datatype: float
      format: "::0.5"
    valid: true

```

2024-12-02 11:26 UTC, Tieske commented on homie5/formats/float.yml
What's missing is the full float format (exp notation, "." as decimal separator, etc.)

2024-12-02 11:26 UTC, Tieske commented on homie5/formats/integer.yml
> +    valid: false
```suggestion
  - description: missing range boundaries is accepted
    testtype: propertydescription
    definition:
      datatype: integer
      format: ":"
    valid: true
```

2024-12-02 11:26 UTC, Tieske commented on homie5/formats/float.yml
> +
```suggestion
  - description: step value larger than range is accepted
    testtype: propertydescription
    definition:
      datatype: float
      format: "0:10:20"
    valid: true

```
The only valid value is "0" in this case. If not valid then it would collide with the `single-point range with step value is accepted` test above.

2024-12-02 11:26 UTC, Tieske commented on homie5/formats/integer.yml
> +
```suggestion

  - description: proper format with only step value is accepted
    testtype: propertydescription
    definition:
      datatype: integer
      format: "::5"
    valid: true

```

2024-12-02 11:26 UTC, Tieske commented on homie5/formats/integer.yml
> +    valid: false
```suggestion
  - description: step value larger than range is accepted
    testtype: propertydescription
    definition:
      datatype: integer
      format: "0:10:20"
    valid: true
```
collides with `single point range with step value is accepted` above

2024-12-02 11:26 UTC, Tieske commented on homie5/values/enum.yml
> +
```suggestion
```
the format is invalid, cannot test this

2024-12-02 11:26 UTC, Tieske commented on homie5/values/enum.yml
> +
```suggestion
```

these are invalid formats

2024-12-02 11:26 UTC, Tieske commented on homie5/formats/integer.yml
> +
```suggestion

  - description: exponent notation in minimum is rejected
    testtype: propertydescription
    definition:
      datatype: integer
      format: "5e1:5000:10"
    valid: false

  - description: exponent notation in maximum is rejected
    testtype: propertydescription
    definition:
      datatype: integer
      format: "50:5e5:10"
    valid: false

  - description: exponent notation in step is rejected
    testtype: propertydescription
    definition:
      datatype: integer
      format: "50:5000:1e2"
    valid: false

  - description: only negative sign in minimum is rejected
    testtype: propertydescription
    definition:
      datatype: integer
      format: "-:10:1"
    valid: false
  
  - description: only negative sign in maximum is rejected
    testtype: propertydescription
    definition:
      datatype: integer
      format: "-5:-:1"
    valid: false

  - description: only negative sign in step is rejected
    testtype: propertydescription
    definition:
      datatype: integer
      format: "5:10:-"
    valid: false

```

2024-12-02 11:26 UTC, Tieske commented on homie5/values/float.yml
to add: exponent notation and absence of leading zero; eg. "-.15" should be accepted

2024-12-02 11:26 UTC, Tieske commented on homie5/values/string.yml
> +
```suggestion

  - description: Valid empty string value
    testtype: propertyvaluestring
    definition:
      datatype: string
    input_data: "\x00"
    output_data: ""
    valid: true

```

2024-12-02 11:33 UTC, nstadigs commented
Don't see these test files as complete for the included `datatype`s. I think missing tests can be added later. But we shouldn't add any tests that are wrong.

2024-12-02 16:13 UTC, Tieske commented
Agreed. If you can review and commit my suggestions, then I think we can merge this set.

2024-12-05 18:50 UTC, nstadigs commented on homie5/values/enum.yml
> +
nice catch

2024-12-06 13:00 UTC, Tieske commented
please do not force-push/rebase just add new commits such that it is easier to track which comments have been resolved. That prevent reviewers from having to review the whole thing from scratch again.

We can still squash just before merging.

Can you resolve the conversations/comments that you updated? then I'll give it another review.

2024-12-06 13:27 UTC, nstadigs commented
> please do not force-push/rebase just add new commits such that it is easier to track which comments have been resolved. That prevent reviewers from having to review the whole thing from scratch again.
> 
> We can still squash just before merging.
> 
> Can you resolve the conversations/comments that you updated? then I'll give it another review.

Oops, sorry. I'm used to Gitlab at work which handles this perfectly, so I didn't really think about it

2024-12-06 13:39 UTC, nstadigs commented
I know I force pushed again, but I did I reset to the commit before in the reflog to get that revision back to add another commit with the changes on top of it, to see if I could fix the comment references here.

2024-12-09 14:40 UTC, Tieske approved these changes
lgtm

2024-12-09 14:41 UTC, merged